apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: bottlerocket-nvidia
spec:
  amiFamily: Bottlerocket
  blockDeviceMappings:
  - deviceName: /dev/xvda
    ebs:
      deleteOnTermination: true
      volumeSize: 4Gi
      volumeType: gp3
  - deviceName: /dev/xvdb
    ebs:
      deleteOnTermination: true
      volumeSize: 150Gi
      volumeType: gp3
      snapshotID: snap-0a15a532d6e3552c2
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required
  role: KarpenterNodeRole-ray-cluster
  securityGroupSelectorTerms:
  - tags:
      karpenter.sh/discovery: ray-cluster
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: ray-cluster
---
apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  annotations:
  name: gpu
spec:
  disruption:
    consolidateAfter: 600s
    consolidationPolicy: WhenEmpty
    expireAfter: 720h
  limits:
    cpu: 1000
    memory: 1000Gi
    nvidia.com/gpu: 50
  template:
    spec:
      nodeClassRef:
        name: bottlerocket-nvidia
      requirements:
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: kubernetes.io/os
        operator: In
        values:
        - linux
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - on-demand
        - spot
      - key: karpenter.k8s.aws/instance-category
        operator: In
        values:
        - g
      - key: karpenter.k8s.aws/instance-generation
        operator: Gt
        values:
        - "4"
      taints:
      - effect: NoSchedule
        key: ray.io/node-type
        value: worker